from .bindings import (
    VERSION,
    # Clipper64,
    ClipperOffset,
    ClipType,
    EndType,
    FillRule,
    JoinType,
    JoinWith,
    PathType,
    Point64,
    PointD,
    PointInPolygonResult,
    Rect64,
    __doc__,
    area,
    difference,
    inflate_paths,
    intersection,
    is_positive,
    make_path,
    point_in_polygon,
    union,
    xor_,
)
