from .bindings import (
    VERSION,
    ClipperOffset,
    ClipType,
    EndType,
    FillRule,
    JoinType,
    JoinWith,
    PathType,
    Point64,
    PointD,
    PointInPolygonResult,
    Rect64,
    __doc__,
    area,
    is_positive,
    point_in_polygon,
)
