### made following this guide: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#workflow-definition

name: Publish to PyPI
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Python distribution
    ### we currently only support macOS and python version 3.13
    runs-on: macos-15
    strategy:
      matrix:
        python-version: [3.13]
    steps:
        - uses: actions/checkout@v5

        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
            ### it's best practice to pin the UV version
            version: "0.9.5" 
            python-version: ${{ matrix.python-version }}
        
        - name: Build the wheel
          run: uv build

        - name: Store the distribution packages
          uses: actions/upload-artifact@v4
          with:
            name: python-package-distributions
            path: dist/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/project/pyclipper2/  
    permissions:
        id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

        